stages:
- release
- deploy

image: docker
services:
  - docker:dind

step-deploy-prod:
  stage: deploy
  script:
    - docker build -t app/arobots-frontend-rails .
    - docker run -d -p 443:80 --rm --name arobots-frontend app/evo-frontend-rails

