stages:
- build
- deploy

image: docker
services:
  - docker:dind

image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  CI_REGISTRY: registry.gitlab.com/ooo-evo/arobots/arobots-frontend-vue 

build:
  stage: build
  before_script: 
    - docker logout $CI_REGISTRY
    - docker login -u $REGISTRY_USERNAME -p $DEPLOY_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY .
    - docker push $CI_REGISTRY



deploy:
  stage: deploy
  before_script:
    - docker logout $CI_REGISTRY
    - docker login -u $REGISTRY_USERNAME -p $DEPLOY_TOKEN $CI_REGISTRY
  script:
    - docker-compose -f frontend-compose.yml down
    - docker-compose -f frontend-compose.yml up -d 
