<template>
  <div>
    <v-card
      flat
      style="margin-left: 8vw; margin-right: 8vw;"
    >
      <h1>Terms of use</h1>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus vel non hic. Rem consequuntur, ea optio repellendus animi suscipit inventore dolorem error necessitatibus ipsa maiores dolores eius, alias voluptatem facilis, sed aut debitis placeat voluptate sit provident facere quasi dignissimos cupiditate. Tempora dolorum esse corporis mollitia, obcaecati veritatis odit aut pariatur. Repellat illum impedit, eos soluta, debitis cupiditate ipsum iusto dignissimos sequi fugiat culpa, quasi nobis molestiae. Architecto odit deserunt, enim aliquam quae tenetur dolores libero hic maiores earum a, inventore recusandae nobis aut eligendi, incidunt reprehenderit ea! Voluptate similique mollitia odit facilis. Optio delectus recusandae accusantium autem accusamus sequi vel quidem quae asperiores excepturi ex harum debitis ipsam tempore, cupiditate voluptates expedita rerum fugit? Corporis, necessitatibus tempore! Dolores ut facilis velit pariatur laudantium enim voluptate? Earum voluptatum quod illo consequuntur alias eaque at quae, ducimus quis quo tempore, quidem delectus fugit eligendi vero ab possimus eveniet nihil ex. Sed asperiores laboriosam aliquam! Magnam voluptatem sunt quae, dicta necessitatibus distinctio reprehenderit quisquam consectetur aperiam culpa animi doloremque harum suscipit, ab iste iusto nihil. Doloremque, omnis possimus? Perferendis libero laboriosam magnam autem quae, inventore cupiditate praesentium natus veniam ipsum doloribus facilis odio corporis recusandae fugiat expedita, consectetur id. Eveniet, saepe soluta!</p>
      <p>Omnis sit ad minima assumenda laboriosam ipsa! Eveniet deserunt, maxime amet vel modi cumque illum ad totam. Sapiente velit officiis dignissimos modi. Rerum eos magnam atque odio perferendis iusto voluptates, facere doloremque debitis blanditiis, eveniet mollitia? Odio, quisquam sequi nulla neque soluta quae, deserunt sit id architecto, magni distinctio ex doloribus consequuntur temporibus nisi! Est architecto et, beatae aliquid quas atque totam ut iure quia soluta veniam deleniti laudantium minima quaerat omnis. Dicta quaerat voluptatem suscipit fugit hic nisi mollitia, dignissimos autem dolores ipsum alias doloribus quos voluptas vero ducimus. Ipsum natus laboriosam nobis, perspiciatis rerum exercitationem blanditiis commodi? Tenetur quam atque deleniti assumenda, ad dolor placeat maiores sed et, modi pariatur ut libero consequatur id. Sit ullam repellendus quasi. Dolore ratione, aperiam placeat itaque dolor voluptate ullam. Eius commodi atque nostrum ut, voluptates iure illum, magnam quisquam amet repellendus deleniti distinctio ea. Ipsum veniam modi quia reiciendis natus numquam unde quo sapiente qui molestiae? Suscipit, aliquid? Earum veniam ea, cumque sunt dignissimos possimus id porro laudantium laborum soluta eaque expedita. Aliquam quibusdam amet libero consequatur est doloremque nobis, cumque, nulla possimus reprehenderit facilis tenetur, id dolores vero autem blanditiis rem fugit. Velit et vero possimus similique soluta quod pariatur?</p>
      <p>Laudantium obcaecati dolorem ducimus dicta eveniet modi repellat saepe pariatur quae reiciendis. Dicta, asperiores nemo! Quae laborum doloremque, architecto commodi sequi, unde rem nulla facere ipsam, repellendus eum sapiente illum ipsa fugit cupiditate repellat voluptas reprehenderit nisi ratione illo aut placeat. Nihil nemo perspiciatis dolore sit itaque rerum eligendi atque sapiente placeat, eum obcaecati commodi repellat quam deserunt cupiditate corporis nulla aliquam dicta harum deleniti? Minus odio illum odit qui eum rerum doloribus atque placeat, exercitationem maiores vel molestiae voluptatibus culpa mollitia, obcaecati, quis sit iusto totam! Excepturi quisquam aperiam ducimus necessitatibus dolorum accusamus, maxime optio minima amet unde asperiores obcaecati expedita delectus! Enim veritatis eius ipsam natus sunt cum, tempore eligendi quae soluta temporibus sit doloribus dolor et nesciunt quas neque aut, recusandae earum omnis aliquam. Architecto suscipit eos, dolorem sequi nemo nihil reprehenderit! Consectetur, alias quae eius eum excepturi odio, numquam et error beatae voluptatem enim cupiditate non suscipit repellendus veritatis quo minus aperiam reiciendis? Tempore neque suscipit exercitationem? Eum reprehenderit laudantium quidem tempore atque voluptas quae! Deleniti vero rem saepe, doloribus dignissimos qui aliquam ea quisquam dolorum quae repellat numquam iste? Natus, sint est? Ea, autem libero, quia ipsum neque alias totam exercitationem possimus nemo fuga numquam.</p>
      <p>Voluptatum, quas molestiae. In quas dolor aut ipsam veniam nihil voluptas, soluta facilis dignissimos perspiciatis reprehenderit quo. Voluptatibus laboriosam adipisci deleniti debitis eligendi earum assumenda aliquam, ducimus veniam alias, consectetur et numquam veritatis libero magni distinctio itaque sequi pariatur consequatur mollitia, sapiente expedita consequuntur tempore qui. Delectus totam iusto labore aliquam at maiores tenetur? Ut commodi minima eius numquam atque voluptatibus illum velit in ipsum officia exercitationem corporis perferendis excepturi unde minus dolorem eaque recusandae, esse labore assumenda magnam dolorum non modi? Laborum, architecto alias, molestias autem recusandae numquam aperiam dolorum in doloremque facere aspernatur dolorem nihil maiores, possimus ad ipsum illo. Eum consectetur tenetur debitis error tempore dolore explicabo ab asperiores, praesentium recusandae. Soluta obcaecati a, optio tenetur in, illo nihil aut vero ipsa, deleniti placeat dicta dignissimos atque labore? Adipisci labore dicta possimus laboriosam neque ducimus, perferendis vero, voluptatem ipsum veniam tempora totam atque accusamus. Dolor maxime reiciendis fugit illo cumque quam dolorem cum blanditiis et officia eum aliquam, tenetur explicabo vel id veniam voluptatem beatae magni, commodi sed omnis eveniet voluptatum iure natus! Excepturi harum veniam possimus neque dolore, fugiat nostrum illum nemo aut exercitationem dolor ab minima hic dolorem similique provident, consectetur beatae ullam doloremque vero.</p>
    </v-card>
  </div>
</template>
